x-common-configuration: &default-configuration
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1 
  volumes:
    - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
    - "$HOME/.Xauthority:/root/.Xauthority:rw"
    - "/dev/:/dev/"

x-cuda-configuration: &cuda-configuration
  runtime: nvidia
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1 
  volumes:
    - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
    - "$HOME/.Xauthority:/root/.Xauthority:rw"
    - "/dev/:/dev/"
  deploy:
    resources:
        reservations:
            devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics, compat32, video, display]

services:
# ==========================================
# Ubuntu 24 + PX4
# ==========================================
  ubicoders_u24_px4:
    container_name: ubicoders_u24_px4_cnt
    build:
      context: .
      dockerfile: ./u24_px4/Dockerfile
    image: ubicoders/px4:v1.16
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    <<: *default-configuration

# ==========================================
# Ubuntu 24 + ROS2 Jazzy
# ==========================================
  ubicoders_ros2_jazzy:
    container_name: ubicoders_ros2_jazzy_cnt
    build:
      context: .
      dockerfile: ./ros2jazzy/Dockerfile
    image: ubicoders/ros2:jazzy
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    <<: *default-configuration

  ubicoders_ros2_jazzy_svo:
    container_name: ubicoders_ros2_jazzy_svo_cnt
    build:
      context: .
      dockerfile: ./ros2svo/Dockerfile
    image: ubicoders/ros2:jazzy_svo
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    <<: *default-configuration    


  ubicoders_ros2_jazzy_vrobots:
    container_name: ubicoders_ros2_jazzy_vrobots_cnt
    build:
      context: .
      dockerfile: ./ros2vrobots/Dockerfile
    image: ubicoders/ros2:jazzy_vrobots
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    <<: *default-configuration    

  ubicoders_ros2_jazzy_svo_vrobots:
    container_name: ubicoders_ros2_jazzy_svo_vrobots_cnt
    build:
      context: .
      dockerfile: ./ros2svo_vrobots/Dockerfile
    image: ubicoders/ros2:jazzy_svo_vrobots
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    <<: *default-configuration    


  ubicoders_ros2_jazzy_px4:
    container_name: ubicoders_ros2_jazzy_px4_cnt
    build: 
      context: .
      dockerfile: ./ros2px4/Dockerfile
    image: ubicoders/ros2:jazzy_px4
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    depends_on:
      - ubicoders_ros2_jazzy
    <<: *default-configuration
  
  ubicoders_ros2_jazzy_px4uxrcedds:
    container_name: ubicoders_ros2_jazzy_px4_uxrcedds_cnt
    build: 
      context: .
      dockerfile: ./ros2px4uxrcedds/Dockerfile
    image: ubicoders/ros2:jazzy_px4_uxrcedds
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    depends_on:
      - ubicoders_ros2_jazzy_px4
    <<: *default-configuration

# ==========================================
# Ubuntu 24 + CUDA 12 - NO ROS2
# ==========================================  
  ubicoders_u24_cuda12:
    container_name: ubicoders_u24_cuda12_cnt
    build: 
      context: .
      dockerfile: ./u24cuda1281/Dockerfile
    image: ubicoders/ubuntu:u24_cuda12
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    <<: *cuda-configuration

  ubicoders_u24_cuda12_ocv_zed:
    container_name: ubicoders_u24_cuda12_ocv_zed_cnt
    build: 
      context: .
      dockerfile: ./u24cuda1281_ocv_zed/Dockerfile
    image: ubicoders/ubuntu:u24_cuda12_ocv_zed
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    depends_on:
    - ubicoders_u24_cuda12
    tty: true        # docker run -t    
    <<: *cuda-configuration

# ==========================================
# Ubuntu 24 + CUDA 12 + ROS2 Jazzy
# ==========================================  
  ubicoders_u24_cuda12_jazzy:
    container_name: ubicoders_u24_cuda12_jazzy_cnt
    build: 
      context: .
      dockerfile: ./u24cuda1281_jazzy/Dockerfile
    image: ubicoders/ros2:jazzy_cuda12
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    depends_on:
    - ubicoders_u24_cuda12
    tty: true        # docker run -t    
    <<: *cuda-configuration    
